# Generated by Django 5.1.2 on 2024-12-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.CharField(max_length=255)),
                ("predicted_class", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
            ],
        ),
    ]
