# Generated by Django 5.1.4 on 2024-12-10 22:40

import project_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_core", "0002_predictionhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionhistory",
            name="predicted_label",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="predictionhistory",
            name="image_path",
            field=models.ImageField(upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="predictionhistory",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="uploadedimage",
            name="image",
            field=models.ImageField(upload_to=project_core.models.upload_to),
        ),
    ]
